name = "MC"
uuid = "769ab3d0-0d7b-11ea-0685-592be65fdeeb"
authors = ["Carl Morris"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
